### ISSUE TITLE
Looking for some newbie help: "Targeted Peak Detection"

### ISSUE THREAD

**Issue by stefanjhill** [mzmine/mzmine2#358] opened 2017-09-06 23:20 UTC
This is where I hope my search terms weren't rubbish or I'm not posting in completely the wrong forum. So in light of a potential bollocking.

I am a new user to MZmine and so far have found my way around doing things. And I've got to grips with processing and online database searching. I must admit I'm impressed that how MZmine does far more than most commercial packages, score 1 point for open source and good will!

But I have run into some trouble, I find I would like to use "Targeted Peak Detection". I have set up a CSV file using the help file that has only one entry to see how it works:

209.1175, 9.28, Jasmonic Acid

When I run this against an imported mxML file I get the error "Could not read file or the file is empty". The mzML file is fine when I do processing all the way to alignment and peak IDing using KEGG. So I guess it's my CSV file at fault.

I set the Targeted Peak Detection parameters to:

Int. tol. = 100%
Noise = 1.0e2
m/z tol. = 0.1 / 5 ppm
RT tol. - 2.0

Would some kind soul take pity on me and give me some advice and suggested parameters to get me started. Once I'm underway with no errors I'll happily play with parameters to optimize things.

Many thanks in advance for any help, and apologies if this is the wrong place to post this,

Cheers,
  Stefan.

**Comment by tomas-pluskal** [comment] 2017-09-07 17:49
Hi,
Could you send the .mzmine project file and your .csv file? That is the easiest way to find the source of the problem.

**Comment by stefanjhill** [comment] 2017-09-07 20:31
Hi Tomas,

Thanks for offering to take a look!

I have left the Aligned peak list in the file, the Peak ID is 1884 that I would like to be able to hunt for using Targeted Peak Detection.

The files can be found on:
https://drive.google.com/open?id=0B33LFhY6Z-dkaGxLbDVKNnBWaVk

Thanks again, really appreciate your help,
   Stefan.

**Comment by tomas-pluskal** [comment] 2017-09-07 23:32
Hi Stefan,
The problem is in the CSV file. If you add a newline after the first line, it is going to work fine. I will try to fix the targeted peak detection module to account for such case.

Also I recommend to set the Intensity tolerance threshold to a lower value, like 50%.

**Comment by stefanjhill** [comment] 2017-09-07 23:42
That is absolutely brilliant!

Works like a charm, that solves my final analysis method problem.

Incredibly grateful,
   Stefan.

**Comment by tomas-pluskal** [comment] 2017-09-17 00:24
So, actually the problem was caused by the 3-byte byte order mark in the CSV file. This is invisible in a text editor, but it caused the MZmine CSV parser to skip the first line. I just pushed a fix for this.

**Comment by tomas-pluskal** [comment] 2017-09-22 00:09
Fixed in version 2.29

**Closed by tomas-pluskal** 2017-09-22 00:09 UTC
