### ISSUE TITLE
MZmine 2.17 - baseline correction fails when run concurrently.

### ISSUE THREAD

**Issue by DrewG** [mzmine/mzmine2#128] opened 2015-10-13 08:13 UTC
Hi,

I'm using MZmine 2.17 on Windows 7 Home Premium SP1 (64 bit).  I've been checking out the baseline correction algorithms and have found that if I try to run more than one at a time, it fails with a dialog-box message saying something like...

"R computing error' during baseline correction.
Rserve error: couldn't collect result for R expression 'baseline' (instance '2660')" (see end of console output).

This happens for all of the baseline correction algs.  I /think/ I tried them all.

So, if I have a project with 2 or more datafiles in it and I attempt to run baseline correction on more than one of them, I get the error.  If I run baseline correction on one at a time, works no problem.  I get the same issue if I try to batch them - MZmine attempts to run them concurrently and fails. 

I can upload a test project to DropBox later this evening - let me know if you need it.

java -version output - 
java version "1.8.0-25"
Java(TM) SE Runtime Environment (build 1.8.0-26.b18)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

R --version output -
R version 3.2.2 (2015-08-14) -- "Fire Safety" 
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform x86_64-w64-mingw32/x64 (64 bit)

error output - 
[9:19:36|FINEST|MainMenu]: Setting parameters for module Baseline correction
09:19.38 1373[dbg] Looping before Zumo is running
09:19.38 1374[dbg] Drive not mounted file not exist
09:19.38 1375[dbg] last print time1444724378
[9:19:43|FINEST|MainMenu]: Starting module Baseline correction with parameters R
aw data files: Blank_QBD1_A2_Pos.mzdata.xml
Blank_QBD1_A1_Pos.mzdata.xml, Filename suffix: baseline-corrected, Chromatogram
type: TIC, MS level: 1, Use m/z bins: true, m/z bin width: 0.1, Correction metho
d: RollingBall baseline corrector, Remove source file after baseline correction:
 false
[9:19:43|FINEST|TaskQueue]: Adding task "Correcting baseline for Blank_QBD1_A2_P
os.mzdata.xml" to the task controller queue
[9:19:43|FINEST|TaskQueue]: Adding task "Correcting baseline for Blank_QBD1_A1_P
os.mzdata.xml" to the task controller queue
[9:19:43|INFO|WorkerThread]: Starting processing of task Correcting baseline for
 Blank_QBD1_A2_Pos.mzdata.xml
[9:19:43|FINEST|RLocationDetection]: Windows: Query registry to find where R is
installed ...
[9:19:43|INFO|WorkerThread]: Starting processing of task Correcting baseline for
 Blank_QBD1_A1_Pos.mzdata.xml
[9:19:43|FINEST|RLocationDetection]: R InstallPath = C:\Program Files\R\R-3.2.2
[9:19:43|FINEST|RLocationDetection]: R executable location auto-detected as 'C:\
Program Files\R\R-3.2.2\bin\R.exe'
09:19.43 1376[dbg] Looping before Zumo is running
09:19.43 1377[dbg] Drive not mounted file not exist
09:19.43 1378[dbg] last print time1444724383
[9:19:44|FINEST|RSessionWrapper]:   failed: timed out
[9:19:44|FINEST|RSessionWrapper]: Connection R://MZmineUser:1251dd98-59a8-4c33-a
792-ddbd0f97c96f@localhost:6311 failed.
[9:19:44|FINEST|RSessionWrapper]: !! Rserve R://MZmineUser:1251dd98-59a8-4c33-a7
92-ddbd0f97c96f@localhost:6311 is not accessible.
 ! null
[9:19:44|FINEST|RSessionWrapper]: Trying to spawn R://MZmineUser:1251dd98-59a8-4
c33-a792-ddbd0f97c96f@localhost:6311
[9:19:44|FINEST|RLocationDetection]: Windows: Query registry to find where R is
installed ...
[9:19:44|FINEST|RSessionWrapper]: Failed to connect: Cannot connect: Connection
refused: connect
[9:19:44|FINEST|RLocationDetection]: R InstallPath = C:\Program Files\R\R-3.2.2
[9:19:44|FINEST|RLocationDetection]: R executable location auto-detected as 'C:\
Program Files\R\R-3.2.2\bin\R.exe'
[9:19:44|FINEST|RSessionWrapper]: starting R daemon... R://MZmineUser:1251dd98-5
9a8-4c33-a792-ddbd0f97c96f@localhost:6311
[9:19:44|FINEST|RSessionWrapper]: Waiting for Rserve to start ...
[9:19:44|FINEST|RSessionWrapper]:   executing "C:\Program Files\R\R-3.2.2\bin\R.
exe" -e "library(Rserve);Rserve(FALSE,args='--no-save --slave  --RS-pidfile "C:/
Users/drew/AppData/Local/Temp/MZmine2015-10-13_08-42-52.233/rs_pid_6311195310965
1555247449.pid" --RS-port 6311')" --no-save --slave
[9:19:44|FINEST|RSessionWrapper]: Rserve startup done, let us try to connect ...

[9:19:45|FINEST|RSessionWrapper]: Rserve is running.
[9:19:45|FINEST|RSessionWrapper]:   ok
[9:19:46|FINEST|RSessionWrapper]: Local Rserve started. (Version 103)
[9:19:46|FINEST|RSessionWrapper]: Rserve: started instance (pid: '2660' | port:
'6311').
[9:19:46|FINEST|RSessionWrapper]: R version 3.2.2 (2015-08-14)
[9:19:46|FINEST|RSessionWrapper]: 103
[9:19:46|FINEST|RSessionWrapper]: UTF-8
[9:19:46|FINEST|RSessionWrapper]: Loading package 'baseline'...
[9:19:46|FINEST|RLocationDetection]: Windows: Query registry to find where R is
installed ...
[9:19:46|FINEST|RLocationDetection]: R InstallPath = C:\Program Files\R\R-3.2.2
[9:19:46|FINEST|RLocationDetection]: R executable location auto-detected as 'C:\
Program Files\R\R-3.2.2\bin\R.exe'
[9:19:46|FINEST|RSessionWrapper]: Load status: 'true'.
[9:19:46|FINEST|RSessionWrapper]: Loaded package: 'baseline'.
[9:19:46|FINEST|BaselineCorrector]: Building TIC chromatograms.
[9:19:46|FINEST|BaselineCorrector]: Calculating baselines.
[9:19:47|FINEST|RSessionWrapper]:     Repeated 100 times.
[9:19:47|FINEST|RSessionWrapper]:   failed: timed out
[9:19:47|FINEST|RSessionWrapper]: Connection R://MZmineUser:1251dd98-59a8-4c33-a
792-ddbd0f97c96f@localhost:6312 failed.
[9:19:47|FINEST|RSessionWrapper]: !! Rserve R://MZmineUser:1251dd98-59a8-4c33-a7
92-ddbd0f97c96f@localhost:6312 is not accessible.
 ! null
[9:19:47|FINEST|RSessionWrapper]: Trying to spawn R://MZmineUser:1251dd98-59a8-4
c33-a792-ddbd0f97c96f@localhost:6312
[9:19:47|FINEST|RLocationDetection]: Windows: Query registry to find where R is
installed ...
[9:19:47|FINEST|RLocationDetection]: R InstallPath = C:\Program Files\R\R-3.2.2
[9:19:47|FINEST|RSessionWrapper]: Failed to connect: Cannot connect: Connection
refused: connect
[9:19:47|FINEST|RLocationDetection]: R executable location auto-detected as 'C:\
Program Files\R\R-3.2.2\bin\R.exe'
[9:19:47|FINEST|RSessionWrapper]: starting R daemon... R://MZmineUser:1251dd98-5
9a8-4c33-a792-ddbd0f97c96f@localhost:6312
[9:19:47|FINEST|RSessionWrapper]: Waiting for Rserve to start ...
[9:19:47|FINEST|RSessionWrapper]:   executing "C:\Program Files\R\R-3.2.2\bin\R.
exe" -e "library(Rserve);Rserve(FALSE,args='--no-save --slave  --RS-pidfile "C:/
Users/drew/AppData/Local/Temp/MZmine2015-10-13_08-42-52.233/rs_pid_6312448297746
7124735177.pid" --RS-port 6312')" --no-save --slave
[9:19:47|FINEST|RSessionWrapper]: Rserve startup done, let us try to connect ...

[9:19:48|FINEST|RSessionWrapper]:     Repeated 100 times.
[9:19:48|FINEST|RSessionWrapper]: Rserve is running.
[9:19:48|FINEST|RSessionWrapper]:   ok
09:19.48 1379[dbg] Looping before Zumo is running
09:19.48 1380[dbg] Drive not mounted file not exist
09:19.48 1381[dbg] last print time1444724388
[9:19:49|FINEST|RSessionWrapper]:     Repeated 100 times.
[9:19:49|FINEST|RSessionWrapper]:     Repeated 100 times.
[9:19:49|FINEST|RSessionWrapper]: Local Rserve started. (Version 103)
[9:19:49|FINEST|RSessionWrapper]: Rserve: started instance (pid: '5952' | port:
'6312').
[9:19:49|FINEST|RSessionWrapper]: R version 3.2.2 (2015-08-14)
[9:19:49|FINEST|RSessionWrapper]: 103
[9:19:49|FINEST|RSessionWrapper]: UTF-8
[9:19:49|FINEST|RSessionWrapper]: Loading package 'baseline'...
[9:19:50|FINEST|RSessionWrapper]: Load status: 'true'.
[9:19:50|FINEST|RSessionWrapper]: Loaded package: 'baseline'.
[9:19:50|FINEST|BaselineCorrector]: Building TIC chromatograms.
[9:19:50|FINEST|BaselineCorrector]: Calculating baselines.
[9:19:50|FINEST|RSessionWrapper]: !     Repeated 59 times.
[9:19:50|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:50|FINEST|RSessionWrapper]: !     Repeated 23 times.
[9:19:50|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:50|FINEST|RSessionWrapper]: !     Repeated 26 times.
[9:19:50|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:50|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:50|FINEST|RSessionWrapper]: !     Repeated 9 times.
[9:19:50|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:50|FINEST|RSessionWrapper]: !     Repeated 18 times.
[9:19:50|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:50|FINEST|RSessionWrapper]: !     Repeated 7 times.
[9:19:50|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:50|FINEST|RSessionWrapper]: !     Repeated 10 times.
[9:19:50|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:50|FINEST|RSessionWrapper]: !     Repeated 4 times.
[9:19:50|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:50|FINEST|RSessionWrapper]: !     Repeated 3 times.
[9:19:50|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:50|FINEST|RSessionWrapper]:     Repeated 1 times.
[9:19:51|FINEST|RSessionWrapper]:     Repeated 100 times.
[9:19:51|FINEST|RSessionWrapper]:     Repeated 100 times.
[9:19:51|FINEST|RSessionWrapper]: !     Repeated 15 times.
[9:19:51|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:51|FINEST|RSessionWrapper]: !     Repeated 21 times.
[9:19:51|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:51|FINEST|RSessionWrapper]:     Repeated 1 times.
[9:19:51|FINEST|RSessionWrapper]: !     Repeated 2 times.
[9:19:51|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:51|FINEST|RSessionWrapper]: !     Repeated 95 times.
[9:19:51|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:51|FINEST|RSessionWrapper]: !     Repeated 89 times.
[9:19:51|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:51|FINEST|RSessionWrapper]: !     Repeated 1 times.
[9:19:51|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:51|FINEST|RSessionWrapper]: !     Repeated 1 times.
[9:19:51|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:51|FINEST|RSessionWrapper]:     Repeated 1 times.
[9:19:52|FINEST|RSessionWrapper]: !     Repeated 28 times.
[9:19:52|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:52|FINEST|RSessionWrapper]: !     Repeated 1 times.
[9:19:52|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:52|FINEST|RSessionWrapper]: !     Repeated 40 times.
[9:19:52|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:52|FINEST|RSessionWrapper]: !!     Repeated 27 times.
 R>
 R! eval failed, request status: error code: 127
[9:19:52|FINEST|RSessionWrapper]: !! [exception] eval failed, request status: er
ror code: 127
  if (!is.null(bl)) { baseline <- getBaseline(bl); } else { baseline <- matrix(r
ep(min(chromatogram), length(chromatogram)), nrow=1); }
 R> [exception] eval failed, request status: error code: 127
  if (!is.null(bl)) { baseline <- getBaseline(bl); } else { baseline <- matrix(r
ep(min(chromatogram), length(chromatogram)), nrow=1); }
 R! eval failed, request status: error code: 127
[9:19:52|FINEST|RSessionWrapper]: !     Repeated 24 times.
[9:19:52|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:52|FINEST|RSessionWrapper]: !     Repeated 49 times.
[9:19:52|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:52|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:52|FINEST|RSessionWrapper]: !     Repeated 11 times.
[9:19:52|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:52|FINEST|RSessionWrapper]: !     Repeated 10 times.
[9:19:52|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:52|FINEST|RSessionWrapper]:     Repeated 2 times.
[9:19:52|FINEST|RSessionWrapper]: !     Repeated 7 times.
[9:19:52|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:52|FINEST|RSessionWrapper]: !     Repeated 8 times.
[9:19:52|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:52|FINEST|RSessionWrapper]: !! [exception] eval failed, request status: er
ror code: 127
  mat <- matrix(chromatogram, nrow=1)
 R> [exception] eval failed, request status: error code: 127
  mat <- matrix(chromatogram, nrow=1)
 R! eval failed, request status: error code: 127
[9:19:52|FINEST|RSessionWrapper]: !     Repeated 42 times.
[9:19:52|FINEST|RSessionWrapper]: ! eval failed, request status: error code: 127

[9:19:52|FINEST|RSessionWrapper]: !!     Repeated 47 times.
 R>
 R! eval failed, request status: error code: 127
[9:19:52|FINEST|RSessionWrapper]: !! [exception] eval failed, request status: er
ror code: 127
  baseline
 R> [exception] eval failed, request status: error code: 127
  baseline
 R! eval failed, request status: error code: 127
[9:19:52|FINEST|RSessionWrapper]: Rserve: try terminate  session (pid: '2660' |
port: '6311')...
[9:19:53|FINEST|RSessionWrapper]: Ending remote session...
[9:19:53|FINEST|RSessionWrapper]: Session teminated.
[9:19:53|FINEST|RSessionWrapper]: Rserve: terminated  session (pid: '2660' | por
t: '6311')...
[9:19:53|SEVERE|WorkerThread]: Error of task Correcting baseline for Blank_QBD1_
A2_Pos.mzdata.xml: 'R computing error' during baseline correction.
Rserve error: couldn't collect result for R expression 'baseline' (instance '266
0').

**Comment by tomas-pluskal** [comment] 2015-10-18 14:16
Hi, 
Thanks for the report. It would be helpful to have a copy of your project file as well.
Gauthier @golgauth, do you have time to investigate this issue?

**Comment by golgauth** [comment] 2015-10-19 10:37
Hi,
I'd love to. I can, at least, start to. But as tomas already asked, I'll would need any material that would help to reproduce the error. This can be R limitations, memory limitation, MZmine side implementation problem, etc.

Thanks
Gauthier

**Comment by DrewG** [comment] 2015-10-19 11:35
Hi, just seeing the replies here.  I will place an example project in dropbox and post a link here this evening.

**Comment by DrewG** [comment] 2015-10-19 21:44
OK @golgauth - a small project can be found at...

https://dl.dropboxusercontent.com/u/46916368/MZmine/baseline%20correction%20error.zip

Datafiles are just a couple of blank chromatography runs.

In the zipfile are a couple of screenshots showing my rolling ball settings, just load the project, go to Raw Data Methods... Filtering... Baseline Correction and run it against all raw datafiles, you should see the error.

Let me know if I can be of any more help.

Drew.

**Comment by golgauth** [comment] 2015-10-21 08:56
Ok, thanks Drew, I'll dig into it on friday. I am sorry I won't have time earlier.
Gauthier

**Comment by golgauth** [comment] 2015-10-27 14:12
Hello all and @DrewG ,
I've been testing several things and it is clear that the issue is Windows specific. I haven't been able to locate and fix the cause for now (I do not have a proper Windows environment for MZmine dev at the time being). So, I'll do my best to get it fixed ASAP, but since I won't have the time for all that in the next few days and if you absolutely need this feature now, I suggest you try running MZmine from a  Linux Live CD, or from a Mac (if you are familiar with any of those plateforms).

Best
Gauthier

**Comment by DrewG** [comment] 2015-10-29 09:05
Hi @golgauth,

No problems.  I'm stuck to Windows at work, but have both OSX and Ubuntu at home if needed.  But as I said, they can be run one at a time no problem, just a little more time consuming.

I hadn't tried it on my Mac though - will do so later.  Cheers :)

**Comment by golgauth** [comment] 2015-12-11 10:06
Hi @DrewG ,

Can you confirm that the latest fix above solves your concurrency problems under Windows, please?
Related commit is e877793.

Thanks a lot by advance. Cheers!

**Comment by Leperkhan** [comment] 2015-12-11 20:17
Somewhat related but is R version 3.2.2 the last version that supports the baseline packages? If I try to install the packages on 3.2.3 it gives me an error about those packages not working for 3.2.3.

**Comment by golgauth** [comment] 2015-12-11 20:43
Hi,

That's not related, like you said. This can happen if `Bioclite` bioconductor packages and/or some of their related dependencies are not up-to-date. Or maybe some of those packages are really not yet available for this release of R. Could you post you configuration (output of `installed.packages()` and any information that can be useful to identify the issue (the error backtrace of MZmine, etc).

Also, since it is not related to this issue, could you please open a new one.
Thanks

Best
Gauthier

**Comment by golgauth** [comment] 2015-12-13 00:29
Hi,

That's not related, like you said. This can happen if `Bioclite` bioconductor packages and/or some of their related dependencies are not up-to-date. Or maybe some of those packages are really not yet available for this release of R. Could you post you configuration (output of `installed.packages()` and any information that can be useful to identify the issue (the error backtrace of MZmine, etc).

Also, since it is not related to this issue, could you please open a new one.
Thanks

Best
Gauthier

**Comment by tomas-pluskal** [comment] 2015-12-13 18:21
@DrewG, 
can you please test this issue with the newly released MZmine 2.18? It should be fixed there.
Tomas

**Comment by golgauth** [comment] 2015-12-18 17:07
This issue is fixed in MZmine 2.18.2 (tested with Drew's data files under Windows 7 successfully). The bug has been clearly identified and fixed (Commit 38152bd). It can be closed safely, by now.

**Closed** 2015-12-18 17:16 UTC

**Comment by DrewG** [comment] 2016-01-05 09:23
Happy New Year all, yes, I can confirm that it's working quite happily on my PC right now in v 2.18.2

Sorry for my late reply.  Keep up the good work !
