### ISSUE TITLE
Gridmass help

### ISSUE THREAD

**Issue by dschief001** [mzmine/mzmine2#684] opened 2019-08-23 07:43 UTC
### Setup

I am reporting a problem with MZmine 2 version 2.41.2. 
My operating system is Win10 64-bit .

### Expected behavior

When Gridmass is opened, and the help button clicked it should open the *GridMass - 2D peak detection* page, instead the 
### Actual behavior
TIC/XIC visualizer is opened.

### Steps to reproduce the problem

Open the Gridmass peak detection dialog and click on Help.

Thanks for fixing

**Comment by tomas-pluskal** [comment] 2019-08-25 15:28
I cannot reproduce this problem, for me the GridMass help page opens. 
Can you try to start MZmine again, go to GridMass and click Help (without taking any other action)?
Does this problem happen for you only with the GridMass module, or also with other modules?

**Comment by tomas-pluskal** [comment] 2019-09-03 20:14
Should be definitely fixed in MZmine 2.50+, because the help system was changed.

**Closed by tomas-pluskal** 2019-09-03 20:14 UTC
