### ISSUE TITLE
Mzmine transition number instead of masses

### ISSUE THREAD

**Issue by OmarSAHMED** [mzmine/mzmine2#789] opened 2020-01-29 15:51 UTC
### Basic information

* My operating system: window 10
* My MZmine version: 2.53

Dear,

I have an issue concerning the use of MSconvert to convert Wiff files (SRM) to MzmL to upload them to Mzmine. The problem is when I use MZmine, the peaks appear with the transition number instead of showing the mass (see figure attached). 

I already contacted Mzmine developer and they said to me that the problem came from MS convert. So, I contacted the Msconvert team and this was there answer,

((Hi Omar,

I assume you're using the srmAsSpectra option or else you would only get chromatograms, not spectra. I'm able to reproduce that behavior of getting transition indexes instead of Q3 masses in srmAsSpectra mode. I fixed that, but the Q1 masses are also missing. And fixing THAT would either require a hacky nativeID format (e.g. "merged=123 sample=1 period=0 experiment=12 cycle=1234 transition=1"), or require a change to the WIFF nativeID format (to add the transition dimension, which would only be used in srmAsSpectra mode, so that's a hacky approach too). In Sciex MRM data, each cycle has multiple transitions in it with different Q1/Q3 values. If all transitions of a cycle shared the same Q1 that would be ok, but they don't. And we can't represent multiple Q1 values in a single mzML spectrum (which is what the API is giving us, what Sciex calls a "cycle"), and I can't split it up into more spectra without using non-standard nativeIDs. Either approach would require more work than I can put on it now. So you'll just have to consider this mode broken.

The best approach, really, would be for mzMine to support reading chromatograms from mzML. Because SRM data is more suitable for representation as chromatograms than as individual scans (by a few orders of magnitude based on file size).))

Any ideas for making mzMine to support reading chromatograms from mzML (MRM)?

Note: attached a photo of the problem.
![Issue](https://user-images.githubusercontent.com/60354865/73372468-4ebb1f80-42c8-11ea-8ef3-b1eb46d40932.jpg)

      Regards
Omar S.AHMED

* Please describe what happened and how it differs from what you expected to happen.
* Please include all parameter values for the MZmine modules you used. 
* Please upload screenshots of any errors and your log/mzmine.log file.
* Please upload an MZmine project file that demonstrates the problem you are reporting.

**Comment by tomas-pluskal** [comment] 2020-01-30 08:10
This seems like a duplicate of #788, no?

**Comment by Annexhc** [comment] 2020-01-30 08:20
yes it is

**Comment by sneumann** [comment] 2020-01-30 18:51
Then please close this one here, seems I can't. Yours, Steffen

**Closed** 2020-01-30 18:52 UTC
