### ISSUE TITLE
Rserve error : couldnt evaluate R code ....

### ISSUE THREAD

**Issue by natalkaeva** [mzmine/mzmine2#243] opened 2016-05-11 15:00 UTC
Hi, I am trying to run the baseline correction and keep running into the following errors. I installed an older version of R (3.2.2) and made sure the packages were loaded. I seem to have a problem launcing any of the R dependent algorithms. 
I am running on Windows 7 and have tested both NetCDF and .raw files. I also tried running the same correction on my Mac (using the NetCDF files). Any ideas if this is a Java issue?
I saw earlier posts and had hoped that MZMine 2.20 might have had these problems resolved. 

Advice appreciated! 

[16:51:23|FINEST|BaselineCorrector]: Calculating baselines.
[16:51:23|FINEST|RSessionWrapper]: !     Repeated 3 times.
[16:51:23|FINEST|RSessionWrapper]: ! [exception] Error in simpleLoess(y, x, w, s
pan, degree, parametric, drop.square, normalize,  :
  sp?nd er for lille

  bseoff <- bslnoff(mat, method="loess", bw=0.0, breaks=breaks, qntl=0.0)
[16:51:23|FINEST|RSessionWrapper]: Rserve: try terminate  session (pid: '2772' |
 port: '6311')...
[16:51:23|FINEST|RSessionWrapper]: Ending remote session...
[16:51:23|FINEST|RSessionWrapper]: Session teminated.
[16:51:23|FINEST|RSessionWrapper]: Rserve: terminated  session (pid: '2772' | po
rt: '6311')...
[16:51:23|SEVERE|WorkerThread]: Error of task Correcting baseline for 20160426_0
4202.CDF: 'R computing error' during baseline correction.
Rserve error: couldn't eval R code 'bseoff <- bslnoff(mat, method="loess", bw=0.
0, breaks=breaks, qntl=0.0)' (instance '2772').
[16:51:24|FINEST|RSessionWrapper]: !! Rserve R://MZmineUser:fa60078d-48df-4ba0-b
291-9ad4910ae6ca@localhost:6312 is not accessible.
 ! null
[16:51:24|FINEST|RSessionWrapper]: Trying to spawn R://MZmineUser:fa60078d-48df-
4ba0-b291-9ad4910ae6ca@localhost:6312
[16:51:24|FINEST|RLocationDetection]: R path set to 'C:\Program Files\R\R-3.2.2\
bin\R.exe' based on MZmine preferences
[16:51:24|FINEST|RSessionWrapper]: starting R daemon... R://MZmineUser:fa60078d-
48df-4ba0-b291-9ad4910ae6ca@localhost:6312

[16:51:25|INFO|WorkerThread]: Starting processing of task Correcting baseline fo
r 20160426_04901.CDF
[16:51:26|FINEST|RSessionWrapper](UTF-8): Local Rserve started. (Version 103)
[16:51:26|FINEST|RSessionWrapper](UTF-8): Rserve: started instance (pid: '1100' | port:
 '6312').
[16:51:26|FINEST|RLocationDetection]: R path set to 'C:\Program Files\R\R-3.2.2\
bin\R.exe' based on MZmine preferences
[16:51:26|FINEST|RSessionWrapper](UTF-8): R version 3.2.2 (2015-08-14)

[16:51:26|FINEST|RSessionWrapper](UTF-8): Loading package 'PROcess'...
[16:51:26|FINEST|RSessionWrapper](UTF-8): Load status: 'true'.
[16:51:26|FINEST|RSessionWrapper](UTF-8): Loaded package: 'PROcess'.
[16:51:26|FINEST|BaselineCorrector]: Building TIC chromatograms.
[16:51:26|FINEST|BaselineCorrector]: Calculating baselines.
[16:51:26|FINEST|RSessionWrapper](UTF-8): !     Repeated 3 times.
[16:51:26|FINEST|RSessionWrapper](UTF-8): ! [exception] Error in simpleLoess(y, x, w, s
pan, degree, parametric, drop.square, normalize,  :
  sp?nd er for lille

  bseoff <- bslnoff(mat, method="loess", bw=0.0, breaks=breaks, qntl=0.0)
[16:51:26|FINEST|RSessionWrapper](UTF-8): Rserve: try terminate  session (pid: '1100' |
 port: '6312')...
[16:51:26|FINEST|RSessionWrapper](UTF-8): Ending remote session...
[16:51:26|FINEST|RSessionWrapper](UTF-8): Session teminated.
[16:51:26|FINEST|RSessionWrapper](UTF-8): Rserve: terminated  session (pid: '1100' | po
rt: '6312')...
[16:51:26|SEVERE|WorkerThread]: Error of task Correcting baseline for 20160426_0
4902.CDF: 'R computing error' during baseline correction.
Rserve error: couldn't eval R code 'bseoff <- bslnoff(mat, method="loess", bw=0.
0, breaks=breaks, qntl=0.0)' (instance '1100').
[16:51:27|FINEST|RSessionWrapper]: !! Rserve R://MZmineUser:fa60078d-48df-4ba0-b
291-9ad4910ae6ca@localhost:6311 is not accessible.
 ! null
[16:51:27|FINEST|RSessionWrapper]: Trying to spawn R://MZmineUser:fa60078d-48df-
4ba0-b291-9ad4910ae6ca@localhost:6311
[16:51:27|FINEST|RLocationDetection]: R path set to 'C:\Program Files\R\R-3.2.2\
bin\R.exe' based on MZmine preferences
[16:51:27|FINEST|RSessionWrapper]: starting R daemon... R://MZmineUser:fa60078d-
48df-4ba0-b291-9ad4910ae6ca@localhost:6311
[16:51:27|INFO|WorkerThread]: Starting processing of task Correcting baseline fo
r 20160428_01802.CDF
[16:51:28|FINEST|RSessionWrapper](ok): Rserve is running.

[16:51:29|FINEST|RSessionWrapper](UTF-8): Local Rserve started. (Version 103)
[16:51:29|FINEST|RLocationDetection]: R path set to 'C:\Program Files\R\R-3.2.2\
bin\R.exe' based on MZmine preferences
[16:51:29|FINEST|RSessionWrapper](UTF-8): Rserve: started instance (pid: '6224' | port:
 '6311').
[16:51:29|FINEST|RSessionWrapper](UTF-8): R version 3.2.2 (2015-08-14)

[16:51:29|FINEST|RSessionWrapper](UTF-8): Loading package 'PROcess'...
[16:51:29|FINEST|RSessionWrapper](UTF-8): Load status: 'true'.
[16:51:29|FINEST|RSessionWrapper](UTF-8): Loaded package: 'PROcess'.
[16:51:29|FINEST|BaselineCorrector]: Building TIC chromatograms.
[16:51:29|FINEST|BaselineCorrector]: Calculating baselines.
[16:51:29|FINEST|RSessionWrapper](UTF-8): !     Repeated 3 times.
[16:51:29|FINEST|RSessionWrapper](UTF-8): ! [exception] Error in simpleLoess(y, x, w, s
pan, degree, parametric, drop.square, normalize,  :
  sp?nd er for lille

  bseoff <- bslnoff(mat, method="loess", bw=0.0, breaks=breaks, qntl=0.0)
[16:51:29|FINEST|RSessionWrapper](UTF-8): Rserve: try terminate  session (pid: '6224' |
 port: '6311')...
[16:51:29|FINEST|RSessionWrapper](UTF-8): Ending remote session...
[16:51:29|FINEST|RSessionWrapper](UTF-8): Session teminated.
[16:51:29|FINEST|RSessionWrapper](UTF-8): Rserve: terminated  session (pid: '6224' | po
rt: '6311')...
[16:51:29|SEVERE|WorkerThread]: Error of task Correcting baseline for 20160428_0
0902.CDF: 'R computing error' during baseline correction.
Rserve error: couldn't eval R code 'bseoff <- bslnoff(mat, method="loess", bw=0.
0, breaks=breaks, qntl=0.0)' (instance '6224').
[16:51:30|FINEST|RSessionWrapper]: !! Rserve R://MZmineUser:fa60078d-48df-4ba0-b
291-9ad4910ae6ca@localhost:6312 is not accessible.
 ! null
[16:51:30|FINEST|RSessionWrapper]: Trying to spawn R://MZmineUser:fa60078d-48df-
4ba0-b291-9ad4910ae6ca@localhost:6312
[16:51:30|FINEST|RLocationDetection]: R path set to 'C:\Program Files\R\R-3.2.2\
bin\R.exe' based on MZmine preferences
[16:51:30|FINEST|RSessionWrapper]: starting R daemon... R://MZmineUser:fa60078d-
48df-4ba0-b291-9ad4910ae6ca@localhost:6312
[16:51:30|INFO|WorkerThread]: Starting processing of task Correcting baseline fo
r 20160428_00901.CDF
[16:51:31|FINEST|RSessionWrapper](ok): Rserve is running.

[16:51:32|FINEST|RSessionWrapper](UTF-8): Local Rserve started. (Version 103)
[16:51:32|FINEST|RSessionWrapper](UTF-8): Rserve: started instance (pid: '6444' | port:
 '6312').
[16:51:32|FINEST|RLocationDetection]: R path set to 'C:\Program Files\R\R-3.2.2\
bin\R.exe' based on MZmine preferences
[16:51:32|FINEST|RSessionWrapper](UTF-8): R version 3.2.2 (2015-08-14)

[16:51:32|FINEST|RSessionWrapper](UTF-8): Loading package 'PROcess'...
[16:51:32|FINEST|RSessionWrapper](UTF-8): Load status: 'true'.
[16:51:32|FINEST|RSessionWrapper](UTF-8): Loaded package: 'PROcess'.
[16:51:32|FINEST|BaselineCorrector]: Building TIC chromatograms.
[16:51:32|FINEST|BaselineCorrector]: Calculating baselines.
[16:51:32|FINEST|RSessionWrapper](UTF-8): !     Repeated 3 times.
[16:51:32|FINEST|RSessionWrapper](UTF-8): ! [exception] Error in simpleLoess(y, x, w, s
pan, degree, parametric, drop.square, normalize,  :
  sp?nd er for lille

  bseoff <- bslnoff(mat, method="loess", bw=0.0, breaks=breaks, qntl=0.0)
[16:51:32|FINEST|RSessionWrapper](UTF-8): Rserve: try terminate  session (pid: '6444' |
 port: '6312')...
[16:51:32|FINEST|RSessionWrapper](UTF-8): Ending remote session...
[16:51:32|FINEST|RSessionWrapper](UTF-8): Session teminated.
[16:51:32|FINEST|RSessionWrapper](UTF-8): Rserve: terminated  session (pid: '6444' | po
rt: '6312')...
[16:51:32|SEVERE|WorkerThread]: Error of task Correcting baseline for 20160426_0
4201.CDF: 'R computing error' during baseline correction.
Rserve error: couldn't eval R code 'bseoff <- bslnoff(mat, method="loess", bw=0.
0, breaks=breaks, qntl=0.0)' (instance '6444').
[16:51:33|FINEST|RSessionWrapper]: !! Rserve R://MZmineUser:fa60078d-48df-4ba0-b
291-9ad4910ae6ca@localhost:6311 is not accessible.
 ! null
[16:51:33|FINEST|RSessionWrapper]: Trying to spawn R://MZmineUser:fa60078d-48df-
4ba0-b291-9ad4910ae6ca@localhost:6311
[16:51:33|FINEST|RLocationDetection]: R path set to 'C:\Program Files\R\R-3.2.2\
bin\R.exe' based on MZmine preferences
[16:51:33|FINEST|RSessionWrapper]: starting R daemon... R://MZmineUser:fa60078d-
48df-4ba0-b291-9ad4910ae6ca@localhost:6311
[16:51:33|INFO|WorkerThread]: Starting processing of task Correcting baseline fo
r 20160428_01801.CDF
[16:51:34|FINEST|RSessionWrapper](ok): Rserve is running.

[16:51:35|FINEST|RSessionWrapper](UTF-8): Local Rserve started. (Version 103)
[16:51:35|FINEST|RLocationDetection]: R path set to 'C:\Program Files\R\R-3.2.2\
bin\R.exe' based on MZmine preferences
[16:51:35|FINEST|RSessionWrapper](UTF-8): Rserve: started instance (pid: '4120' | port:
 '6311').
[16:51:35|FINEST|RSessionWrapper](UTF-8): R version 3.2.2 (2015-08-14)

[16:51:35|FINEST|RSessionWrapper](UTF-8): Loading package 'PROcess'...
[16:51:35|FINEST|RSessionWrapper](UTF-8): Load status: 'true'.
[16:51:35|FINEST|RSessionWrapper](UTF-8): Loaded package: 'PROcess'.
[16:51:35|FINEST|BaselineCorrector]: Building TIC chromatograms.
[16:51:35|FINEST|BaselineCorrector]: Calculating baselines.
[16:51:35|FINEST|RSessionWrapper](UTF-8): !     Repeated 3 times.
[16:51:35|FINEST|RSessionWrapper](UTF-8): ! [exception] Error in simpleLoess(y, x, w, s
pan, degree, parametric, drop.square, normalize,  :
  sp?nd er for lille

  bseoff <- bslnoff(mat, method="loess", bw=0.0, breaks=breaks, qntl=0.0)
[16:51:35|FINEST|RSessionWrapper](UTF-8): Rserve: try terminate  session (pid: '4120' |
 port: '6311')...
[16:51:35|FINEST|RSessionWrapper](UTF-8): Ending remote session...
[16:51:35|FINEST|RSessionWrapper](UTF-8): Session teminated.
[16:51:35|FINEST|RSessionWrapper](UTF-8): Rserve: terminated  session (pid: '4120' | po
rt: '6311')...
[16:51:35|SEVERE|WorkerThread]: Error of task Correcting baseline for 20160428_0
1802.CDF: 'R computing error' during baseline correction.
Rserve error: couldn't eval R code 'bseoff <- bslnoff(mat, method="loess", bw=0.
0, breaks=breaks, qntl=0.0)' (instance '4120').
[16:51:36|FINEST|RSessionWrapper]: !! Rserve R://MZmineUser:fa60078d-48df-4ba0-b
291-9ad4910ae6ca@localhost:6312 is not accessible.
 ! null
[16:51:36|FINEST|RSessionWrapper]: Trying to spawn R://MZmineUser:fa60078d-48df-
4ba0-b291-9ad4910ae6ca@localhost:6312
[16:51:36|FINEST|RLocationDetection]: R path set to 'C:\Program Files\R\R-3.2.2\
bin\R.exe' based on MZmine preferences
[16:51:36|FINEST|RSessionWrapper]: starting R daemon... R://MZmineUser:fa60078d-
48df-4ba0-b291-9ad4910ae6ca@localhost:6312

[16:51:38|FINEST|RSessionWrapper](UTF-8): Local Rserve started. (Version 103)
[16:51:38|FINEST|RLocationDetection]: R path set to 'C:\Program Files\R\R-3.2.2\
bin\R.exe' based on MZmine preferences
[16:51:38|FINEST|RSessionWrapper](UTF-8): Rserve: started instance (pid: '3116' | port:
 '6312').
[16:51:38|FINEST|RSessionWrapper](UTF-8): R version 3.2.2 (2015-08-14)

[16:51:38|FINEST|RSessionWrapper](UTF-8): Loading package 'PROcess'...
[16:51:38|FINEST|RSessionWrapper](UTF-8): Load status: 'true'.
[16:51:38|FINEST|RSessionWrapper](UTF-8): Loaded package: 'PROcess'.
[16:51:38|FINEST|BaselineCorrector]: Building TIC chromatograms.
[16:51:38|FINEST|BaselineCorrector]: Calculating baselines.
[16:51:38|FINEST|RSessionWrapper](UTF-8): !     Repeated 3 times.
[16:51:38|FINEST|RSessionWrapper](UTF-8): ! [exception] Error in simpleLoess(y, x, w, s
pan, degree, parametric, drop.square, normalize,  :
  sp?nd er for lille

  bseoff <- bslnoff(mat, method="loess", bw=0.0, breaks=breaks, qntl=0.0)
[16:51:38|FINEST|RSessionWrapper](UTF-8): Rserve: try terminate  session (pid: '3116' |
 port: '6312')...
[16:51:38|FINEST|RSessionWrapper](UTF-8): Ending remote session...
[16:51:38|FINEST|RSessionWrapper](UTF-8): Session teminated.
[16:51:38|FINEST|RSessionWrapper](UTF-8): Rserve: terminated  session (pid: '3116' | po
rt: '6312')...
[16:51:38|SEVERE|WorkerThread]: Error of task Correcting baseline for 20160426_0
4901.CDF: 'R computing error' during baseline correction.
Rserve error: couldn't eval R code 'bseoff <- bslnoff(mat, method="loess", bw=0.
0, breaks=breaks, qntl=0.0)' (instance '3116').
[16:51:39|FINEST|RSessionWrapper]: !! Rserve R://MZmineUser:fa60078d-48df-4ba0-b
291-9ad4910ae6ca@localhost:6311 is not accessible.
 ! null
[16:51:39|FINEST|RSessionWrapper]: Trying to spawn R://MZmineUser:fa60078d-48df-
4ba0-b291-9ad4910ae6ca@localhost:6311
[16:51:39|FINEST|RLocationDetection]: R path set to 'C:\Program Files\R\R-3.2.2\
bin\R.exe' based on MZmine preferences
[16:51:39|FINEST|RSessionWrapper]: starting R daemon... R://MZmineUser:fa60078d-
48df-4ba0-b291-9ad4910ae6ca@localhost:6311

[16:51:41|FINEST|RSessionWrapper](UTF-8): Local Rserve started. (Version 103)
[16:51:41|FINEST|RLocationDetection]: R path set to 'C:\Program Files\R\R-3.2.2\
bin\R.exe' based on MZmine preferences
[16:51:41|FINEST|RSessionWrapper](UTF-8): Rserve: started instance (pid: '6824' | port:
 '6311').
[16:51:41|FINEST|RSessionWrapper](UTF-8): R version 3.2.2 (2015-08-14)

[16:51:41|FINEST|RSessionWrapper](UTF-8): Loading package 'PROcess'...
[16:51:41|FINEST|RSessionWrapper](UTF-8): Load status: 'true'.
[16:51:41|FINEST|RSessionWrapper](UTF-8): Loaded package: 'PROcess'.
[16:51:41|FINEST|BaselineCorrector]: Building TIC chromatograms.
[16:51:41|FINEST|BaselineCorrector]: Calculating baselines.
[16:51:41|FINEST|RSessionWrapper](UTF-8): !     Repeated 3 times.
[16:51:41|FINEST|RSessionWrapper](UTF-8): ! [exception] Error in simpleLoess(y, x, w, s
pan, degree, parametric, drop.square, normalize,  :
  sp?nd er for lille

  bseoff <- bslnoff(mat, method="loess", bw=0.0, breaks=breaks, qntl=0.0)
[16:51:41|FINEST|RSessionWrapper](UTF-8): Rserve: try terminate  session (pid: '6824' |
 port: '6311')...
[16:51:41|FINEST|RSessionWrapper](UTF-8): Ending remote session...
[16:51:41|FINEST|RSessionWrapper](UTF-8): Session teminated.
[16:51:41|FINEST|RSessionWrapper](UTF-8): Rserve: terminated  session (pid: '6824' | po
rt: '6311')...
[16:51:41|SEVERE|WorkerThread]: Error of task Correcting baseline for 20160428_0
1801.CDF: 'R computing error' during baseline correction.
Rserve error: couldn't eval R code 'bseoff <- bslnoff(mat, method="loess", bw=0.
0, breaks=breaks, qntl=0.0)' (instance '6824').
[16:51:42|FINEST|RSessionWrapper]: !! Rserve R://MZmineUser:fa60078d-48df-4ba0-b
291-9ad4910ae6ca@localhost:6312 is not accessible.
 ! null
[16:51:42|FINEST|RSessionWrapper]: Trying to spawn R://MZmineUser:fa60078d-48df-
4ba0-b291-9ad4910ae6ca@localhost:6312
[16:51:42|FINEST|RLocationDetection]: R path set to 'C:\Program Files\R\R-3.2.2\
bin\R.exe' based on MZmine preferences
[16:51:42|FINEST|RSessionWrapper]: starting R daemon... R://MZmineUser:fa60078d-
48df-4ba0-b291-9ad4910ae6ca@localhost:6312

[16:51:44|FINEST|RSessionWrapper](UTF-8): Local Rserve started. (Version 103)
[16:51:44|FINEST|RSessionWrapper](UTF-8): Rserve: started instance (pid: '2348' | port:
 '6312').
[16:51:44|FINEST|RSessionWrapper](UTF-8): R version 3.2.2 (2015-08-14)

[16:51:44|FINEST|RSessionWrapper](UTF-8): Loading package 'PROcess'...
[16:51:44|FINEST|RSessionWrapper](UTF-8): Load status: 'true'.
[16:51:44|FINEST|RSessionWrapper](UTF-8): Loaded package: 'PROcess'.
[16:51:44|FINEST|BaselineCorrector]: Building TIC chromatograms.
[16:51:44|FINEST|BaselineCorrector]: Calculating baselines.
[16:51:44|FINEST|RSessionWrapper](UTF-8): !     Repeated 3 times.
[16:51:44|FINEST|RSessionWrapper](UTF-8): ! [exception] Error in simpleLoess(y, x, w, s
pan, degree, parametric, drop.square, normalize,  :
  sp?nd er for lille

  bseoff <- bslnoff(mat, method="loess", bw=0.0, breaks=breaks, qntl=0.0)
[16:51:44|FINEST|RSessionWrapper](UTF-8): Rserve: try terminate  session (pid: '2348' |
 port: '6312')...
[16:51:44|FINEST|RSessionWrapper](UTF-8): Ending remote session...
[16:51:44|FINEST|RSessionWrapper](UTF-8): Session teminated.
[16:51:44|FINEST|RSessionWrapper](UTF-8): Rserve: terminated  session (pid: '2348' | po
rt: '6312')...
[16:51:44|SEVERE|WorkerThread]: Error of task Correcting baseline for 20160428_0
0901.CDF: 'R computing error' during baseline correction.
Rserve error: couldn't eval R code 'bseoff <- bslnoff(mat, method="loess", bw=0.
0, breaks=breaks, qntl=0.0)' (instance '2348').

**Comment by tomas-pluskal** [comment] 2016-05-13 19:43
Hi, 
Unfortunately, the link between Java and R has always been causing problems, hard to say what is causing this one.
Gauthier @golgauth , any idea?

**Comment by golgauth** [comment] 2016-05-17 09:22
Well,
Usually, those errors depend on a combination between the nature of the signal being baselined and the chosen set of parameters. It is often a limitation of the R algorithms themselves and I guess limits for those parameters should be defined from MZmine side to prevent errors to happen. But those limits non trivial to define...

I can't tell, unless I have set of data are even an .mzmine project file to attach to your comment such that I can reproduce the issue and eventually provide a fix.

Cheers

**Comment by natalkaeva** [comment] 2016-08-09 13:52
Hi golgaulth,

Many thanks (all those weeks ago) for your reply. I am finally back on this project and trying to get MZmine working. I am still having the issue with Rserve errors (even though it certainly is installed in the version of R I am running, 3.2.2).
All of my project files are well over the size limitations here, and when I've tried to attach a zipfile, I am told that file type isnt supported. How can I get a project file to you?

Would appreciate any advice you can give!

natalka.

**Comment by golgauth** [comment] 2017-07-04 13:44
Hi Tomas,

Did @natalkaeva found a way to provide a test file? I guess not and this was 1 year ago...

**Comment by golgauth** [comment] 2017-07-04 14:28
Pull Request #322 aims to fix this issue (not sure since the error message does not match perfectly): Seems like "loess" method doesn't support "bw=0.0" in:

> Rserve error: couldn't eval R code 'bseoff <- bslnoff(mat, method="loess", bw=0.
> 0, breaks=breaks, qntl=0.0)' (instance '2348').

```
simpleLoess(y, x, w, span, degree, parametric, drop.square, normalize, :
span is too small
```

Pretty high probability this was the issue. Anyway we'll never now ;)

**Comment by tomas-pluskal** [comment] 2017-07-06 14:20
Thanks, I'll happily close this.

**Closed by tomas-pluskal** 2017-07-06 14:20 UTC
Labels: R issue
