### ISSUE TITLE
Problem searching PubChem database

### ISSUE THREAD

**Issue by victoriacha** [mzmine/mzmine2#297] opened 2017-04-27 09:43 UTC
MZmine 2.24
MacOS Sierra 10.12.3 64-bit
Java version 1.8.0_73
R version 3.2.3

Hello,
I receive this message when trying to search my peak list with the PubChem database:
<img width="663" alt="screenshot 2017-04-27 11 39 06" src="https://cloud.githubusercontent.com/assets/28092255/25477575/4da37cfe-2b3e-11e7-86c3-927b6352d062.png">
Thanks for your help,
Victoria

**Comment by tomas-pluskal** [comment] 2017-04-27 14:21
Hi,
I saw this error before, I think this was caused by some limitation in the Java SSL implementation, but I think they fixed it eventually. Please try installing the latest JDK (8u131) and see if that helps.

**Comment by tomas-pluskal** [comment] 2017-04-27 14:31
Hmm, it seems the issue is fixed in Java 9 development tree (https://bugs.openjdk.java.net/browse/JDK-8072452), but the fix has not been backported to Java 8 yet (https://bugs.openjdk.java.net/browse/JDK-8168015).

Strangely enough, it seems to work fine with Java 7.

**Comment by victoriacha** [comment] 2017-04-28 09:22
Hi,
Thanks for your quick response. I installed Java 9 early access for Mac and it's working for me now.
Cheers,
Victoria

**Closed** 2017-05-03 16:05 UTC
