### ISSUE TITLE
Error starting MZmine2

### ISSUE THREAD

**Issue by jammerz7** [mzmine/mzmine2#251] opened 2016-06-25 22:34 UTC
I have a mac. 
Originally I couldn't get it to work because it wouldn't recognize that I had the latest version of Java, then I downloaded JDK. But it still won't start.

Checking physical memory size...
Found 4096 MB memory
Java maximum heap size set to 2048 MB
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

Error: Could not find or load main class net.sf.mzmine.main.MZmineCore
logout

[Process completed]

**Comment by tomas-pluskal** [comment] 2016-06-26 01:20
Hi. Congrats to having a mac.

Do you have _lib_, _conf_, and _icons_ folders in your MZmine folder? Does the _lib_ folder have a file called _mzmine-2.20.jar_?

**Comment by tomas-pluskal** [comment] 2016-07-07 23:23
Can I close this issue now?

**Comment by butterbear1230** [comment] 2016-08-10 20:35
I have the same quesion when I run the MZmine, and I checked the file, I have the file called mzmine-2.20.jar. So what should I do now?

**Comment by tomas-pluskal** [comment] 2016-08-10 21:02
Hi,
Are you seeing exactly the same message in the console (Error: Could not find or load main class net.sf.mzmine.main.MZmineCore)?
Have you tried (re)installing the latest Java JDK from java.oracle.com?
Try running 'java -version' on the Windows command line and send me the  output.

**Comment by butterbear1230** [comment] 2016-08-10 22:18
[cid:333074c0-d2aa-444f-983f-209912a9817e]

just like this.



Ran

________________________________

**Comment by tomas-pluskal** [comment] 2016-08-10 23:23
There was no attachment with your message.

**Comment by butterbear1230** [comment] 2016-08-11 15:41
the problem is solved. Thank you so much for your help


ran

________________________________

**Comment by tomas-pluskal** [comment] 2016-08-11 15:43
So you're not even going to tell us how you solved it?

**Comment by butterbear1230** [comment] 2016-08-11 15:47
sorry, I reinstalled the Java, and ran the cmd JAVA -VERSION, JAVAC. So I thought my JAVA was good to go. Then I found out the problem was I did not unzip my MZMine files. It was really awkward. Anyway the software is okay now. Again, thank you for your help.



Ran

________________________________

**Comment by butterbear1230** [comment] 2016-08-12 16:18
Hi, Tomas.


Sorry to trouble you again. I have a question may need you help with. Can MZmine 2.2.1 software accept Agilent .CSV form files as raw data import?


Thank you.



Ran

________________________________

**Comment by tomas-pluskal** [comment] 2016-08-14 15:24
https://github.com/mzmine/mzmine2/blob/master/src/main/java/net/sf/mzmine/modules/rawdatamethods/rawdataimport/fileformats/AgilentCsvReadTask.java

**Comment by irockafe** [comment] 2017-08-10 19:11
I'm having the same error ("Error: Could not find or load main class net.sf.mzmine.main.MZmineCore") on Ubuntu 14.04 (64bit), downloaded mzmine2 from the github today (2017-10-08)

> **./startMZmine_Linux.sh**
*Checking physical memory size...*
*Found 11694 MB memory*
*Java maximum heap size set to 9646 MB*
*java version "1.8.0_144"*
*Java(TM) SE Runtime Environment (build 1.8.0_144-b01)*
*Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)*

*Error: Could not find or load main class net.sf.mzmine.main.MZmineCore*

I updated my java and downloaded the JDK:

**Java and SDK version:**
> **java -version**
*java version "1.8.0_144"*
*Java(TM) SE Runtime Environment (build 1.8.0_144-b01)*
*Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)*

>**javac -version**
*javac 1.8.0_144*

Final note: 
I cannot find a file called *mzmine-2.20.jar*, nor can I find a *conf/* folder in the downloaded zip file.

**Comment by tomas-pluskal** [comment] 2017-08-10 19:17
Which ZIP file did you download, precisely?
MZmine releases are here: https://github.com/mzmine/mzmine2/releases

**Closed** 2017-08-25 13:06 UTC

**Comment by irockafe** [comment] 2017-08-29 18:16
Downloaded v2.28 from the releases page and everything starts up fine. My guess is that I downloaded directly from the github instead of the releases page (face = palm).

**Comment by Aniket-Pradhan** [comment] 2018-02-05 10:34
Hi Tomas

I cloned the mzmine2 repo after forking it to my account. Later I found out that MZMine when executed from the same repo, produces the same error, i.e.
 java.lang.ClassNotFoundException: net.sf.mzmine.main.MZmineCore

I also found that the script files: startMZmine_Linux.sh is not executable by default. Hence, I ran the script through bash, which gave me the above error.
The file _mzmine-2.20.jar_ is also not present in the whole repo.
I also tried updating the JDK to JDK SE 9.0.1 version, but no luck.

The file present in the releases page, i.e. MZmine 2.30 is working fine, however, this version has some problems.

**Comment by tomas-pluskal** [comment] 2018-02-05 11:50
The repo containd the source codes, it is not meant to be executable unless you compile the source codes. Perhaps you should stick to the official releases.

**Comment by Aniket-Pradhan** [comment] 2018-02-05 12:04
How do I compile the source codes?

`mvn clean package`?

**Comment by Aniket-Pradhan** [comment] 2018-02-05 12:41
Yup. That worked.

Thanks Tomas. :)

**Comment by tomas-pluskal** [comment] 2018-02-05 12:41
Yes
